schema = 2
language = "java"
srcml_flags = ["-r", "-j", "4", "--src-encoding=UTF-8"]

[srcml]
version = "1.1.0"

[[projects]]
name = "jdk"
repo = "https://github.com/openjdk/jdk.git"
tag = "jdk-21+35"
exclude_files = [
    "src/jdk.jpackage/windows/classes/jdk/jpackage/internal/WixTool.java",
    "test/langtools/tools/javac/ConditionalExpressionResolvePending.java",
    "test/langtools/tools/javac/classfiles/attributes/EnclosingMethod/EnclosingMethodTest.java",
    "test/langtools/tools/javac/patterns/AnnotationErrors.java",
    "test/langtools/tools/javac/patterns/AnnotationErrors.out",
    "test/langtools/tools/javac/patterns/Annotations.java",
    "test/langtools/tools/javac/patterns/BindingsExistTest.java",
    "test/langtools/tools/javac/patterns/BindingsExistTest.out",
    "test/langtools/tools/javac/patterns/BindingsInitializer.java",
    "test/langtools/tools/javac/patterns/BindingsTest1.java",
    "test/langtools/tools/javac/patterns/BindingsTest1Merging.java",
    "test/langtools/tools/javac/patterns/BindingsTest1Merging.out",
    "test/langtools/tools/javac/patterns/BindingsTest2.java",
    "test/langtools/tools/javac/patterns/BindingsTest2.out",
    "test/langtools/tools/javac/patterns/BreakAndLoops.java",
    "test/langtools/tools/javac/patterns/CaseStructureTest.java",
    "test/langtools/tools/javac/patterns/CastConversionMatch.java",
    "test/langtools/tools/javac/patterns/CastConversionMatch.out",
    "test/langtools/tools/javac/patterns/ConditionalTest.java",
    "test/langtools/tools/javac/patterns/DeconstructionDesugaring.java",
    "test/langtools/tools/javac/patterns/DeconstructionPatternErrors.java",
    "test/langtools/tools/javac/patterns/DeconstructionPatternErrors.out",
    "test/langtools/tools/javac/patterns/DisambiguatePatterns.java",
    "test/langtools/tools/javac/patterns/Domination.java",
    "test/langtools/tools/javac/patterns/Domination.out",
    "test/langtools/tools/javac/patterns/DuplicateBindingTest.java",
    "test/langtools/tools/javac/patterns/DuplicateBindingTest.out",
    "test/langtools/tools/javac/patterns/EmptyRecordClass.java",
    "test/langtools/tools/javac/patterns/EnsureTypesOrderTest.java",
    "test/langtools/tools/javac/patterns/EnsureTypesOrderTest.out",
    "test/langtools/tools/javac/patterns/EnumTypeChanges.java",
    "test/langtools/tools/javac/patterns/EnumTypeChanges2.java",
    "test/langtools/tools/javac/patterns/EnumTypeChangesNonPreview.java",
    "test/langtools/tools/javac/patterns/ExamplesFromProposal.java",
    "test/langtools/tools/javac/patterns/Exhaustiveness.java",
    "test/langtools/tools/javac/patterns/GenericRecordDeconstructionPattern.java",
    "test/langtools/tools/javac/patterns/Guards.java",
    "test/langtools/tools/javac/patterns/GuardsErrors.java",
    "test/langtools/tools/javac/patterns/GuardsErrors.out",
    "test/langtools/tools/javac/patterns/ImpossibleTypeTest.java",
    "test/langtools/tools/javac/patterns/ImpossibleTypeTest.out",
    "test/langtools/tools/javac/patterns/InferenceUnitTest.java",
    "test/langtools/tools/javac/patterns/InstanceofTotalPattern-15.out",
    "test/langtools/tools/javac/patterns/InstanceofTotalPattern-16.out",
    "test/langtools/tools/javac/patterns/InstanceofTotalPattern-20.out",
    "test/langtools/tools/javac/patterns/InstanceofTotalPattern.java",
    "test/langtools/tools/javac/patterns/LambdaCannotCapturePatternVariables.java",
    "test/langtools/tools/javac/patterns/LocalVariableReuse.java",
    "test/langtools/tools/javac/patterns/LocalVariableTable.java",
    "test/langtools/tools/javac/patterns/MatchBindingScopeTest.java",
    "test/langtools/tools/javac/patterns/MatchBindingScopeTest.out",
    "test/langtools/tools/javac/patterns/MatchExceptionTest.java",
    "test/langtools/tools/javac/patterns/NestedDeconstructionPattern.java",
    "test/langtools/tools/javac/patterns/NestedPatternVariablesBytecode.java",
    "test/langtools/tools/javac/patterns/NestedPrimitiveDeconstructionPattern.java",
    "test/langtools/tools/javac/patterns/NewCaseStructureTest.java",
    "test/langtools/tools/javac/patterns/NoModifiersOnBinding.java",
    "test/langtools/tools/javac/patterns/NoModifiersOnBinding.out",
    "test/langtools/tools/javac/patterns/NoSubtypeCheck.java",
    "test/langtools/tools/javac/patterns/NoSubtypeCheck.out",
    "test/langtools/tools/javac/patterns/NoUnnecessaryCast.java",
    "test/langtools/tools/javac/patterns/NullSwitch.java",
    "test/langtools/tools/javac/patterns/NullsInDeconstructionPatterns.java",
    "test/langtools/tools/javac/patterns/NullsInDeconstructionPatterns.out",
    "test/langtools/tools/javac/patterns/NullsInDeconstructionPatterns2.java",
    "test/langtools/tools/javac/patterns/NullsInPatterns.java",
    "test/langtools/tools/javac/patterns/NullsInPatterns.out",
    "test/langtools/tools/javac/patterns/Parenthesized.java",
    "test/langtools/tools/javac/patterns/Parenthesized.out",
    "test/langtools/tools/javac/patterns/PatternCaseErrorRecovery.java",
    "test/langtools/tools/javac/patterns/PatternCaseErrorRecovery.out",
    "test/langtools/tools/javac/patterns/PatternDesugaring.java",
    "test/langtools/tools/javac/patterns/PatternErrorRecovery-old.out",
    "test/langtools/tools/javac/patterns/PatternErrorRecovery.java",
    "test/langtools/tools/javac/patterns/PatternErrorRecovery.out",
    "test/langtools/tools/javac/patterns/PatternMatchPosTest.java",
    "test/langtools/tools/javac/patterns/PatternMatchPosTest.out",
    "test/langtools/tools/javac/patterns/PatternMatchPosTestData.java",
    "test/langtools/tools/javac/patterns/PatternTypeTest2.java",
    "test/langtools/tools/javac/patterns/PatternVariablesAreNonFinal.java",
    "test/langtools/tools/javac/patterns/PatternVariablesAreNonFinal.out",
    "test/langtools/tools/javac/patterns/PatternVariablesAreNonFinal2.java",
    "test/langtools/tools/javac/patterns/PatternsSimpleVisitorTest.java",
    "test/langtools/tools/javac/patterns/PrettyTest.java",
    "test/langtools/tools/javac/patterns/ProxyMethodLookup.java",
    "test/langtools/tools/javac/patterns/RawTypeBindingWarning.java",
    "test/langtools/tools/javac/patterns/RawTypeBindingWarning.out",
    "test/langtools/tools/javac/patterns/Reifiable.java",
    "test/langtools/tools/javac/patterns/Reifiable.out",
    "test/langtools/tools/javac/patterns/ReifiableOld-old.out",
    "test/langtools/tools/javac/patterns/ReifiableOld.java",
    "test/langtools/tools/javac/patterns/ReifiableOld.out",
    "test/langtools/tools/javac/patterns/ScopeResizeTest.java",
    "test/langtools/tools/javac/patterns/SealedTypeChanges.java",
    "test/langtools/tools/javac/patterns/SealedTypeChanges2.java",
    "test/langtools/tools/javac/patterns/SimpleAndGuardPattern.java",
    "test/langtools/tools/javac/patterns/SimpleDeconstructionPattern.java",
    "test/langtools/tools/javac/patterns/SimpleDeconstructionPatternOld.out",
    "test/langtools/tools/javac/patterns/SourceLevelChecks.java",
    "test/langtools/tools/javac/patterns/StablePatternDesugaring.java",
    "test/langtools/tools/javac/patterns/SwitchErrors.java",
    "test/langtools/tools/javac/patterns/SwitchErrors.out",
    "test/langtools/tools/javac/patterns/Switches.java",
    "test/langtools/tools/javac/patterns/T8291657.java",
    "test/langtools/tools/javac/patterns/T8309054.java",
    "test/langtools/tools/javac/patterns/T8309054.out",
    "test/langtools/tools/javac/patterns/TranslationTest.java",
    "test/langtools/tools/javac/patterns/TypedDeconstructionPatternExc.java",
    "test/langtools/tools/javac/patterns/UncheckedWarningOnMatchesTest.java",
    "test/langtools/tools/javac/patterns/UncheckedWarningOnMatchesTest.out",
    "test/langtools/tools/javac/patterns/Unnamed.java",
    "test/langtools/tools/javac/patterns/UnnamedErrors.java",
    "test/langtools/tools/javac/patterns/UnnamedErrors.out",
    "test/langtools/tools/javac/patterns/VarErrors.java",
    "test/langtools/tools/javac/patterns/VarErrors.out",
    "test/langtools/tools/javac/patterns/scope/ScopeTest.java",
    "test/langtools/tools/javac/patterns/scope/TEST.properties",
    "test/langtools/tools/javac/platform/NumericalComparatorTest.java",
    "test/langtools/tools/javac/recovery/ClassBlockExits.java",
]
current_baseline_release = ""
