schema = 2
language = "java"
srcml_flags = ["-r", "-j", "4", "--src-encoding=UTF-8"]

[srcml]
version = "1.1.0"

[[projects]]
name = "jdk"
repo = "https://github.com/openjdk/jdk.git"
tag = "jdk-21+35"
subdir = "src"
exclude_files = [
    "src/jdk.jpackage/windows/classes/jdk/jpackage/internal/WixTool.java",
]
current_baseline_release = ""
